<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE colores [
 <!ELEMENT colores (color,ANY,color)>
 <!ELEMENT color (#PCDATA)>
]>
<colores>
 <color>azul marino</color>
 negro
 <color>amarillo</color>
</colores> 
<!--DTD Corregido-->

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE colores [
 <!ELEMENT colores (color*)>
 <!ELEMENT color (#PCDATA)>
]>
<colores>
 <color>azul marino</color>
 <color>amarillo</color>
</colores> 
<!--XML Corregido-->